package com.borabora.ws.soaphandlers.client;

import com.borabora.ws.soaphandlers.client.autogenerated.Balance;
import com.borabora.ws.soaphandlers.client.autogenerated.PaymentsService;
import com.borabora.ws.soaphandlers.client.autogenerated.PaymentsServiceService;
import com.borabora.ws.soaphandlers.client.autogenerated.Transaction;
import com.borabora.ws.soaphandlers.client.handler.MessageHeaderLogger;

import javax.xml.ws.Binding;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.handler.Handler;
import java.util.List;

/**
 * Created by mrbueno on 02/08/15.
 */
public class Main {
    public static void main(String[] args) {
        System.out.println("Client started...");
        PaymentsServiceService service = new PaymentsServiceService();
        PaymentsService paymentsServicePort = service.getPaymentsServicePort();

        // Adding handler by handler chain
        Binding binding = ((BindingProvider) paymentsServicePort).getBinding();
        List<Handler> handlerList = binding.getHandlerChain();
        handlerList.add(new MessageHeaderLogger());
        binding.setHandlerChain(handlerList);
        // Adding handler by handler resolver
        service.setHandlerResolver(new CustomHandlerResolver());

        Transaction t = new Transaction();
        t.setId(22l);
        t.setMoney(222d);
        Balance pay = paymentsServicePort.pay(t);
        System.out.println("pay.getMoney() = " + pay.getMoney());
    }
}
