
package com.borabora.ws.soaphandlers.client.autogenerated;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PaymentsService", targetNamespace = "http://service.server.soaphandlers.ws.borabora.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PaymentsService {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.borabora.ws.soaphandlers.client.autogenerated.Balance
     */
    @WebMethod
    @WebResult(name = "balance", targetNamespace = "")
    @RequestWrapper(localName = "pay", targetNamespace = "http://service.server.soaphandlers.ws.borabora.com/", className = "com.borabora.ws.soaphandlers.client.autogenerated.Pay")
    @ResponseWrapper(localName = "payResponse", targetNamespace = "http://service.server.soaphandlers.ws.borabora.com/", className = "com.borabora.ws.soaphandlers.client.autogenerated.PayResponse")
    @Action(input = "http://service.server.soaphandlers.ws.borabora.com/PaymentsService/payRequest", output = "http://service.server.soaphandlers.ws.borabora.com/PaymentsService/payResponse")
    public Balance pay(
        @WebParam(name = "arg0", targetNamespace = "")
        Transaction arg0);

}
